services:
  server:
    build: .
    command: python server.py
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build: .
    command: python /app/client.py
    volumes:
      - data:/app/data
    depends_on:
      server:
        condition: service_healthy
    environment:
      - NUM_CLIENTS=${NUM_CLIENTS:-3}

volumes:
  data: